### ISSUE TITLE
#01 Create index page for introduction 

### ISSUE THREAD

**Issue by jonatannapolesoliveira** [jonasnapoles/my-website#1]
- [x] Structure the index page with blade to header, Nav and footer
- [x] Add article with a slideshow component

**Comment by jonatannapolesoliveira** [comment]
Use laravel 9.0 and php 8.0

**Comment by jonasnapoles** [comment]
I'd like to create six versions:

Tech:

- First version: WordPress
- Second version: Drupal
- Third version: PHP (Laravel 9), JavaScript(React 18.2.0), MySQL, CSS (Bootstrap) and HTML.
- Fourth version: Python (Django), JavaScript (React 18.2.0), MySQL, CCS (Bootstrap) and HTML.
- Fifth version: .Net, JavaScript (React 18.2.0), MySQL, CSS (Tailwind CSS) and HTML.
- Sixth version: JavaScript (React 18.2.0), Node.js(Express.js), MySQL, CSS (Bootstrap) and HTML.
- Last version: Java (Spring), MySQL, CSS (Bootstrap) and HTML.

**Comment by jonatannapolesoliveira** [comment]
fix(#7 ): Updated setup
